---
fixtures:
  repositories:
    stdlib:
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    nsswitch:
      repo: 'https://github.com/trlinkin/puppet-nsswitch.git'
  symlinks:
    pam: "#{source_dir}"
